const status = {
    ALREADY_EXIST: 422,
    INVALID_ACCESS_TOKEN: 401,
    INVALID_CREDENTIAL: 403,
    SUCCESS_STATUS: 200,
    CREATE: 201,
    NO_DATA_FOUND: 200,
    PARAMETER_MISSING_STATUS: 400,
    SHOW_ERROR_MESSAGE: 400,
    ERROR_IN_EXECUTION: 404,
    BAD_REQUEST_STATUS: 500
}
module.exports = {status}